# Keep clipboard content after app closes
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0 &

# Watch clipboard and store history
exec-once=wl-paste --type text --watch cliphist store &

# Polkit
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# swayidle
exec-once=swayidle -w timeout 600 'swaylock -f' timeout 900 'wlr-dpms off' before-sleep 'swaylock' after-resume 'wlr-dpms on' timeout 900 'systemctl suspend'

# General
exec-once=waybar
exec-once=awww-daemon
exec-once=udev-block-notify
exec-once=swaync
