# --- Main Colors ---
background            #141218
foreground            #e6e1e9
cursor                #e6e1e9
cursor_text_color     #141218

selection_background  #494458
selection_foreground  #e8def8

url_color             #efb8c9

# --- ANSI Colors ---
color0                #141218
color1                #ffb4ab
color2                #efb8c9
color3                #cbc3dc
color4                #cebdfe
color5                #efb8c9
color6                #cbc3dc
color7                #e6e1e9

color8                #48454e
color9                #93000a
color10               #633b49
color11               #494458
color12               #4c3e76
color13               #494458
color14               #633b49
color15               #cac4cf

# --- Starship Prompt Bubbles ---
color255              #4c3e76
color254              #cebdfe
color253              #494458
color252              #cbc3dc
color251              #633b49
color250              #efb8c9
color249              #93000a
color248              #ffb4ab

color232              #e8ddff
color233              #35275d
color234              #e8def8
color235              #332e41
color236              #ffd9e3
color237              #492532
color238              #ffdad6
color239              #690005
color240              #e8ddff

# Matched with unthemed light/dark
color243              #cebdfe
color244              #ffb4ab
color245              #48454e

# --- UI Elements ---
active_tab_foreground   #35275d
active_tab_background   #cebdfe
inactive_tab_foreground #e8ddff
inactive_tab_background #4c3e76

active_border_color     #cebdfe
inactive_border_color   #938f99

# --- Marks ---
mark1_foreground        #201047
mark1_background        #e8ddff
mark2_foreground        #1d192b
mark2_background        #e8def8
mark3_foreground        #31101d
mark3_background        #ffd9e3
