rootcolor=141218ff

bordercolor=48454eff

focuscolor=cebdfeff

maximizescreencolor=cbc3dcff

urgentcolor=ffb4abff

scratchpadcolor=efb8c9ff

globalcolor=494458ff

overlaycolor=633b49ff

jump_label_decorate_fg_color=e8def8ff

jump_label_decorate_bg_color=e6e1e9ff

jump_label_decorate_border_color=cebdfeff
