# Waterfox
windowrule=isfloating:1,appid:waterfox,title:About Waterfox
windowrule=isfloating:1,appid:waterfox,title:Picture-in-Picture

# Thunar
windowrule=isfloating:1,appid:thunar,title:Rename
windowrule=isfloating:1,appid:thunar,title:File Operation Progress
windowrule=isfloating:1,appid:thunar,title:Confirm to replace files
windowrule=isfloating:1,appid:xfce-polkit,title:Authentication required

# Ark
windowrule=isfloating:1,appid:ark,title:Extract

# Waypaper
windowrule=isfloating:1,appid:waypaper

# nmrs
windowrule=isfloating:1,appid:nmrs
