# Waterfox
windowrule=isfloating:1,appid:waterfox,title:About Waterfox
windowrule=isfloating:1,appid:waterfox,title:Picture-in-Picture

# Dolphin
windowrule=isfloating:1,appid:dolphin,title:Extract

# Ark
windowrule=isfloating:1,appid:ark,title:Extract

# Waypaper
windowrule=isfloating:1,appid:waypaper

# nmrs
windowrule=isfloating:1,appid:nmrs

# pavucontrol
windowrule=isfloating:1,appid:pavucontrol

# blueman
windowrule=isfloating:1,appid:blueman-manager